### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by negipo** [t9md/atom-recent-finder#2]
[Enter steps to reproduce:]

1. Open Atom
2. run `Recent Finder: Toggle`

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [recent-finder](https://github.com/t9md/atom-recent-finder) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'apply' of undefined

```
At /Users/po/.atom/packages/recent-finder/lib/main.coffee:51

TypeError: Cannot read property 'apply' of undefined
    at View.getEmptyMessage (/packages/recent-finder/lib/main.coffee:51:7)
    at View.FuzzyFinderView (/app.asar/node_modules/fuzzy-finder/lib/fuzzy-finder-view.js:58:26)
    at /packages/recent-finder/lib/main.coffee:40:3)
    at Object.getView (/packages/recent-finder/lib/main.coffee:106:14)
    at /packages/recent-finder/lib/main.coffee:94:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
 10x -1:15.5.0 vim-mode-plus:move-down-screen (input.hidden-input)
  4x -1:15 vim-mode-plus:move-up-screen (input.hidden-input)
     -1:14.2.0 vim-mode-plus:activate-linewise-visual-mode (input.hidden-input)
     -1:14 vim-mode-plus:yank (input.hidden-input)
     -1:11.3.0 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
     -1:09.2.0 editor:consolidate-selections (input.hidden-input)
     -1:09.2.0 core:cancel (input.hidden-input)
  2x -1:07.6.0 vim-mode-plus:move-down-screen (input.hidden-input)
     -1:05.2.0 window:focus-pane-on-left (input.hidden-input)
 96x -1:04.9.0 vim-mode-plus:move-down-screen (input.hidden-input)
 69x -1:02.2.0 vim-mode-plus:move-up-screen (input.hidden-input)
 35x -0:59.8.0 vim-mode-plus:move-down-screen (input.hidden-input)
 22x -0:50.8.0 vim-mode-plus:move-up-screen (input.hidden-input)
  9x -0:09.7.0 vim-mode-plus:move-down-screen (input.hidden-input)
     -0:08.8.0 window:focus-pane-on-right (input.hidden-input)
     -0:07.0 recent-finder:toggle (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-fuzzy-grep 0.16.0 
auto-update-packages 1.0.1 
close-other-panes 0.6.0 
close-pane-with-moving-items 0.8.0 
css-snippets 1.1.0 
file-explorer 0.3.0 
file-icons 2.1.3 
find-selection 0.16.0 
git-plus undefined 
language-digdag 0.0.2 
language-gitignore 0.3.0 
language-haml 0.24.1 
language-matlab 0.2.1 
language-plantuml 0.2.0 
language-rspec 0.6.1 
markdown-scroll-sync 2.1.2 
merge-conflicts 1.4.4 
monokai 0.22.0 
open-recent 5.0.0 
pen-paper-coffee-syntax 0.14.9 
permanent-delete 0.1.5 
pigments 0.39.1 
plantuml-viewer 0.7.1 
project-manager 3.3.4 
quick-highlight 0.8.1 
rails-finder 0.6.0 
rails-snippets 2.15.0 
rails-transporter 1.6.5 
recent-finder 0.5.0 
rspec 0.3.2 
rspec-snippets 0.4.0 
set-syntax 0.3.2 
show-ideographic-space 1.0.2 
solarized-dark-ui 0.3.2 
symbols-tree-view 0.14.0 
sync-settings 0.8.1 
trailing-spaces 0.4.0 
tree-view-git-status 1.3.1 
vim-mode-plus 0.89.0 
vim-mode-plus-move-to-symbols 0.2.0 
wordcount 2.10.4 
Zen 0.16.4 
```

**Comment by negipo** [comment]
fix confirmed! thank you :D
